/**
 * Audio Test Guide - 핵심 테스트 곡 데이터
 *
 * 생성 기준일: 2026-10-04
 * 수록 범위: 최초 추천 해외 10곡 + 한국 10곡
 *
 * 중요:
 * 1. 타임라인은 최종 채택한 스트리밍/영상 버전을 확인하기 전까지 seconds=null로 둔다.
 * 2. 외부 링크는 안전하게 검색 URL로 제공한다. 실제 트랙/영상 ID는 별도 검증 후 추가한다.
 * 3. 앨범, 발매 정보와 권리 제공 상태는 서비스 공개 전 공식 출처로 재검수한다.
 * 4. 평가는 절대적인 '정답 소리'가 아니라 동일 사용자의 기기 비교를 위한 기준이다.
 */

export type TestCategory =
  | "sub-bass"
  | "bass-control"
  | "midrange"
  | "treble"
  | "imaging"
  | "detail"
  | "dynamics"
  | "transient"
  | "timbre"
  | "comfort";

export type VocalType =
  | "instrumental"
  | "male"
  | "female"
  | "mixed"
  | "female-group"
  | "mixed-group";

export type SoundSourceType =
  | "acoustic"
  | "electronic"
  | "acoustic-mixed"
  | "electronic-mixed";

export type VerificationStatus = "TODO_VERIFY" | "VERIFIED";

export interface ListeningGuide {
  seconds: number | null;
  timeLabel: string;
  title: string;
  description: string;
  status: VerificationStatus;
}

export interface ExternalService {
  provider: "YouTube Music" | "Spotify" | "Apple Music" | "Melon";
  kind: "search";
  url: string;
  status: "SEARCH_LINK";
  note: string;
}

export interface AudioTestTrack {
  id: string;
  title: string;
  artist: string;
  album: string;
  releaseInfo: string;
  country: string;
  isKorean: boolean;
  genres: string[];
  vocalType: VocalType;
  performanceType: SoundSourceType;
  ensembleSize: "small" | "medium" | "large" | "variable";
  durationClass: "short" | "medium" | "long" | "unknown";
  durationSeconds: number | null;
  difficulty: "beginner" | "intermediate" | "advanced";
  primaryCategory: TestCategory;
  secondaryCategories: TestCategory[];
  oneLineReason: string;
  estimatedTestTime: string;
  favoriteDefault: false;
  completedDefault: false;
  whySuitable: string;
  listeningFocus: string[];
  listeningGuide: ListeningGuide[];
  goodPlaybackExamples: string[];
  warningSigns: string[];
  evaluationFields: TestCategory[];
  freeMemoDefault: "";
  nextTrackIds: string[];
  comparisonTrackIds: string[];
  externalServices: ExternalService[];
  versionInfo: {
    preferredVersion: string;
    timelineVerified: false;
    metadataStatus: VerificationStatus;
    serviceVersionNote: string;
  };
  sources: {
    status: VerificationStatus;
    required: string[];
  };
  addedAt: "2026-10-04";
}

const serviceSearchLinks = (artist: string, title: string): ExternalService[] => {
  const query = encodeURIComponent(`${artist} ${title}`);
  return [
    {
      provider: "YouTube Music",
      kind: "search",
      url: `https://music.youtube.com/search?q=${query}`,
      status: "SEARCH_LINK",
      note: "공식 아티스트·음반사·권리 보유자 제공 버전을 우선 선택",
    },
    {
      provider: "Spotify",
      kind: "search",
      url: `https://open.spotify.com/search/${query}`,
      status: "SEARCH_LINK",
      note: "앨범명과 발매 버전을 확인한 뒤 재생",
    },
    {
      provider: "Apple Music",
      kind: "search",
      url: `https://music.apple.com/us/search?term=${query}`,
      status: "SEARCH_LINK",
      note: "국가별 제공 여부와 Dolby Atmos 버전 적용 여부 확인",
    },
    {
      provider: "Melon",
      kind: "search",
      url: `https://www.melon.com/search/total/index.htm?q=${query}`,
      status: "SEARCH_LINK",
      note: "한국 서비스 검색 링크이며 음원 버전과 앨범 정보를 확인",
    },
  ];
};

const unverifiedGuide = (focus: string[]): ListeningGuide[] =>
  focus.map((item, index) => ({
    seconds: null,
    timeLabel: "TODO",
    title: `체크 포인트 ${index + 1}`,
    description: item,
    status: "TODO_VERIFY",
  }));

export const AUDIO_TEST_TRACKS: AudioTestTrack[] = [

  {
    id: "eagles-hotel-california-hell-freezes-over",
    title: "Hotel California",
    artist: "Eagles",
    album: "Hell Freezes Over",
    releaseInfo: "1994 · 라이브 버전",
    country: "미국",
    isKorean: false,
    genres: ["록", "어쿠스틱 록", "라이브"],
    vocalType: "male",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "long",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "imaging",
    secondaryCategories: ["bass-control", "timbre", "dynamics"],
    oneLineReason: "라이브 공간, 기타의 위치, 타악기와 저음의 층을 한 번에 확인하기 좋은 곡이다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "도입부의 기타와 타악기는 좌우 위치와 무대 깊이를 비교하기 쉽고, 본 편성이 들어오면 보컬 중심과 여러 기타의 층, 저음의 제어력을 함께 확인할 수 있다. 넓게 들리는 것만으로 공간 표현이 정확하다고 단정하지 말고, 각 소리의 위치가 안정적으로 이어지는지 살핀다. 저음이 풍성한 기기와 킥·베이스의 시작과 끝을 분명하게 표현하는 기기는 다를 수 있다. 라이브 녹음의 관객음과 잔향은 원래 음원에 포함된 정보이므로, 이를 모두 기기의 착색으로 오해하지 않는다.",
    listeningFocus: ["도입부 타악기의 좌우 위치와 잔향", "어쿠스틱 기타 현의 어택과 몸통 울림", "보컬이 중앙에 안정적으로 맺히는지", "후반 합주에서 기타·베이스·드럼의 분리"],
    listeningGuide: unverifiedGuide(["도입부 타악기의 좌우 위치와 잔향", "어쿠스틱 기타 현의 어택과 몸통 울림", "보컬이 중앙에 안정적으로 맺히는지", "후반 합주에서 기타·베이스·드럼의 분리"]),
    goodPlaybackExamples: ["타악기와 기타의 위치가 또렷하지만 서로 단절되지 않는다.", "저음이 충분히 내려가면서도 보컬과 기타를 가리지 않는다."],
    warningSigns: ["무대가 넓기만 하고 중앙 이미지가 비어 보인다.", "저음 잔향이 길게 남아 다음 타격과 겹친다."],
    evaluationFields: ["imaging", "bass-control", "timbre", "dynamics"],
    freeMemoDefault: "",
    nextTrackIds: ["yosi-horikawa-bubbles", "hugh-masekela-stimela"],
    comparisonTrackIds: ["nils-lofgren-keith-dont-go", "dave-brubeck-take-five"],
    externalServices: serviceSearchLinks("Eagles", "Hotel California"),
    versionInfo: {
      preferredVersion: "Hell Freezes Over 수록 라이브 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "michael-jackson-billie-jean",
    title: "Billie Jean",
    artist: "Michael Jackson",
    album: "Thriller",
    releaseInfo: "1982",
    country: "미국",
    isKorean: false,
    genres: ["팝", "펑크", "R&B"],
    vocalType: "male",
    performanceType: "electronic-mixed",
    ensembleSize: "medium",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "bass-control",
    secondaryCategories: ["transient", "midrange", "detail"],
    oneLineReason: "반복되는 베이스와 킥을 통해 저음의 양보다 제어력과 리듬 탄력을 비교하기 쉽다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "곡 전체에 반복되는 베이스와 킥은 기기 간 저음 차이를 빠르게 드러낸다. 핵심은 저음이 크게 들리는지가 아니라 킥의 타격과 베이스 음정이 분리되고, 각 박자의 시작과 끝이 흐려지지 않는지 확인하는 것이다. 보컬이 들어온 뒤에도 저역이 중음을 덮지 않아야 하며 손뼉, 하이햇과 작은 효과음이 리듬 속에서 자연스럽게 보여야 한다. 원래 믹스의 단단하고 건조한 성격을 기기의 공간감 부족으로 단정하지 않는다.",
    listeningFocus: ["킥과 베이스 라인의 분리", "베이스 음정 변화의 추적", "중앙 보컬의 선명도", "손뼉과 하이햇의 짧은 어택"],
    listeningGuide: unverifiedGuide(["킥과 베이스 라인의 분리", "베이스 음정 변화의 추적", "중앙 보컬의 선명도", "손뼉과 하이햇의 짧은 어택"]),
    goodPlaybackExamples: ["킥은 단단하게 치고 베이스는 별도의 선율로 따라갈 수 있다.", "낮은 음이 커져도 보컬의 발음과 리듬이 유지된다."],
    warningSigns: ["킥과 베이스가 하나의 둔한 덩어리로 들린다.", "고역 타격음이 지나치게 날카롭거나 금속적으로 튄다."],
    evaluationFields: ["bass-control", "transient", "midrange", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["lorde-royals", "dean-half-moon"],
    comparisonTrackIds: ["fleetwood-mac-dreams", "newjeans-ditto"],
    externalServices: serviceSearchLinks("Michael Jackson", "Billie Jean"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "norah-jones-dont-know-why",
    title: "Don't Know Why",
    artist: "Norah Jones",
    album: "Come Away with Me",
    releaseInfo: "2002",
    country: "미국",
    isKorean: false,
    genres: ["재즈 팝", "보컬 재즈", "포크"],
    vocalType: "female",
    performanceType: "acoustic",
    ensembleSize: "small",
    durationClass: "short",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "midrange",
    secondaryCategories: ["timbre", "detail", "comfort"],
    oneLineReason: "가까운 여성 보컬과 소규모 어쿠스틱 편성으로 중음의 자연스러움과 질감을 확인하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "보컬이 과도하게 자극적이지 않은 편이라 중음의 두께, 호흡, 발음과 피아노·기타의 질감을 차분히 비교할 수 있다. 좋은 재생은 목소리를 무조건 앞으로 밀어내기보다 악기 사이에서 안정적으로 중심을 잡고, 입 모양과 호흡의 세부를 자연스럽게 보여 준다. 고해상도처럼 들리게 하려고 치찰음이나 기타 현의 마찰음을 과장하는 기기는 처음에는 선명하지만 오래 들으면 피곤할 수 있다. 녹음 자체의 친밀한 보컬 배치를 모든 곡에 적용되는 기기 특성으로 일반화하지 않는다.",
    listeningFocus: ["보컬의 입 모양과 호흡", "피아노 어택과 잔향의 연결", "기타 현의 질감", "작은 음량에서 가사 전달력"],
    listeningGuide: unverifiedGuide(["보컬의 입 모양과 호흡", "피아노 어택과 잔향의 연결", "기타 현의 질감", "작은 음량에서 가사 전달력"]),
    goodPlaybackExamples: ["보컬에 몸통과 온기가 있으면서 발음이 뭉개지지 않는다.", "악기의 세부가 들리지만 보컬보다 과도하게 튀지 않는다."],
    warningSigns: ["보컬이 얇고 치찰음만 강조된다.", "피아노와 기타가 같은 질감으로 평평하게 들린다."],
    evaluationFields: ["midrange", "timbre", "detail", "comfort"],
    freeMemoDefault: "",
    nextTrackIds: ["radka-toneff-moon-harsh-mistress", "akmu-how-can-i-love-heartbreak"],
    comparisonTrackIds: ["kim-kwang-seok-wind-blows", "yoo-jae-ha-because-i-love-you"],
    externalServices: serviceSearchLinks("Norah Jones", "Don't Know Why"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "daft-punk-giorgio-by-moroder",
    title: "Giorgio by Moroder",
    artist: "Daft Punk",
    album: "Random Access Memories",
    releaseInfo: "2013",
    country: "프랑스",
    isKorean: false,
    genres: ["일렉트로닉", "디스코", "펑크"],
    vocalType: "male",
    performanceType: "electronic-mixed",
    ensembleSize: "large",
    durationClass: "long",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "dynamics",
    secondaryCategories: ["detail", "bass-control", "transient"],
    oneLineReason: "내레이션에서 대규모 전자·어쿠스틱 편성으로 확장되어 복잡한 구간의 여유와 분리도를 확인하기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "초반 내레이션의 위치와 배경 노이즈, 이어지는 신시사이저·베이스·드럼·현악 레이어를 단계적으로 비교할 수 있다. 곡이 커질수록 소리가 단순히 시끄러워지는지, 각 층의 윤곽과 리듬이 유지되는지를 확인한다. 다이내믹은 최대 음량만을 뜻하지 않으며 작은 구간과 큰 구간의 대비, 타격의 순간적인 변화까지 포함한다. 저음이 많은 기기가 반드시 빠른 베이스를 정확히 표현하는 것은 아니다. 선택한 스트리밍 버전의 음량 정규화 여부도 결과에 영향을 줄 수 있다.",
    listeningFocus: ["초반 음성의 중앙 위치와 주변 배경음", "신시사이저와 베이스가 추가되는 층의 변화", "드럼 타격의 시작과 멈춤", "후반 대편성에서 악기별 윤곽"],
    listeningGuide: unverifiedGuide(["초반 음성의 중앙 위치와 주변 배경음", "신시사이저와 베이스가 추가되는 층의 변화", "드럼 타격의 시작과 멈춤", "후반 대편성에서 악기별 윤곽"]),
    goodPlaybackExamples: ["편성이 커져도 리듬과 주요 악기의 위치를 계속 따라갈 수 있다.", "강한 타격에서 소리가 눌리거나 거칠어지지 않는다."],
    warningSigns: ["후반부가 하나의 큰 소음처럼 뭉친다.", "저음이 길게 번져 빠른 리듬의 속도를 늦춘다."],
    evaluationFields: ["dynamics", "detail", "bass-control", "transient"],
    freeMemoDefault: "",
    nextTrackIds: ["snarky-puppy-lingus", "aespa-supernova"],
    comparisonTrackIds: ["hans-zimmer-mountains", "park-hyo-shin-wild-flower"],
    externalServices: serviceSearchLinks("Daft Punk", "Giorgio by Moroder"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "nils-lofgren-keith-dont-go",
    title: "Keith Don't Go",
    artist: "Nils Lofgren",
    album: "Acoustic Live",
    releaseInfo: "1997 · 라이브 버전",
    country: "미국",
    isKorean: false,
    genres: ["어쿠스틱 록", "라이브"],
    vocalType: "male",
    performanceType: "acoustic",
    ensembleSize: "small",
    durationClass: "long",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "transient",
    secondaryCategories: ["imaging", "timbre", "detail"],
    oneLineReason: "어쿠스틱 기타의 빠른 어택, 현의 울림과 공연장 잔향을 세밀하게 비교하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "강한 스트로크와 빠른 피킹은 트랜지언트, 즉 소리가 시작되는 순간의 속도와 선명도를 확인하는 데 유용하다. 기타 현의 금속성만 강조되는지, 나무 몸통의 울림과 공연장 잔향까지 균형 있게 이어지는지 살핀다. 세부가 많이 들린다고 항상 자연스러운 것은 아니며, 손가락 마찰음이 음악보다 앞서면 고역이 과장되었을 수 있다. 라이브 녹음의 넓은 공간과 관객 반응은 원본에 포함된 요소다. 음량을 높이면 어택이 더 인상적으로 느껴지므로 A/B 비교에서는 음량을 맞춘다.",
    listeningFocus: ["첫 스트로크의 즉각적인 반응", "현과 기타 몸통 울림의 비율", "연주자의 위치와 공연장 잔향", "빠른 피킹에서 음이 겹치지 않는지"],
    listeningGuide: unverifiedGuide(["첫 스트로크의 즉각적인 반응", "현과 기타 몸통 울림의 비율", "연주자의 위치와 공연장 잔향", "빠른 피킹에서 음이 겹치지 않는지"]),
    goodPlaybackExamples: ["현의 시작이 빠르면서 몸통 울림과 잔향이 자연스럽게 이어진다.", "빠른 연주에서도 각 음의 윤곽이 유지된다."],
    warningSigns: ["현의 마찰음만 날카롭게 튀고 몸통이 비어 보인다.", "잔향이 과장되어 연속 음이 흐려진다."],
    evaluationFields: ["transient", "imaging", "timbre", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["eagles-hotel-california-hell-freezes-over", "yosi-horikawa-letter"],
    comparisonTrackIds: ["kim-kwang-seok-wind-blows", "stevie-ray-vaughan-tin-pan-alley"],
    externalServices: serviceSearchLinks("Nils Lofgren", "Keith Don't Go"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "dave-brubeck-take-five",
    title: "Take Five",
    artist: "The Dave Brubeck Quartet",
    album: "Time Out",
    releaseInfo: "1959",
    country: "미국",
    isKorean: false,
    genres: ["재즈", "쿨 재즈"],
    vocalType: "instrumental",
    performanceType: "acoustic",
    ensembleSize: "small",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "imaging",
    secondaryCategories: ["treble", "transient", "timbre"],
    oneLineReason: "소규모 재즈 편성의 위치, 색소폰 음색, 심벌과 드럼 솔로를 쉽게 구분할 수 있다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "색소폰, 피아노, 베이스와 드럼의 역할이 명확해 악기 위치와 음색을 배우기 좋은 곡이다. 심벌이 밝고 선명하더라도 얇고 모래알처럼 거칠게 부서지지 않는지, 색소폰이 중앙 부근에서 충분한 몸통을 유지하는지 확인한다. 드럼 솔로에서는 타격 위치와 북의 크기, 잔향 차이가 느껴지는지 들어본다. 오래된 녹음의 특성과 현대 음원의 극저역·초고역 확장을 같은 기준으로 비교하지 않는다. 리마스터에 따라 음색과 음량이 달라질 수 있으므로 버전을 기록한다.",
    listeningFocus: ["색소폰의 중심 위치와 몸통", "심벌의 금속성 및 감쇠", "피아노·베이스의 좌우 배치", "드럼 솔로의 타격 위치와 크기"],
    listeningGuide: unverifiedGuide(["색소폰의 중심 위치와 몸통", "심벌의 금속성 및 감쇠", "피아노·베이스의 좌우 배치", "드럼 솔로의 타격 위치와 크기"]),
    goodPlaybackExamples: ["각 악기가 분리되면서도 하나의 밴드처럼 자연스럽게 연결된다.", "심벌의 끝이 길게 이어져도 날카롭거나 입자감이 거칠지 않다."],
    warningSigns: ["색소폰이 지나치게 얇거나 비음만 강조된다.", "드럼 솔로의 여러 북이 비슷한 한 가지 소리로 들린다."],
    evaluationFields: ["imaging", "treble", "transient", "timbre"],
    freeMemoDefault: "",
    nextTrackIds: ["miles-davis-so-what", "hugh-masekela-stimela"],
    comparisonTrackIds: ["norah-jones-dont-know-why", "hoff-ensemble-song-for-olabi"],
    externalServices: serviceSearchLinks("The Dave Brubeck Quartet", "Take Five"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "lorde-royals",
    title: "Royals",
    artist: "Lorde",
    album: "Pure Heroine",
    releaseInfo: "2013",
    country: "뉴질랜드",
    isKorean: false,
    genres: ["팝", "일렉트로팝"],
    vocalType: "female",
    performanceType: "electronic",
    ensembleSize: "small",
    durationClass: "short",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "sub-bass",
    secondaryCategories: ["midrange", "imaging", "bass-control"],
    oneLineReason: "낮은 전자 저음과 중앙 보컬의 공존을 통해 초저음 확장과 중음 마스킹을 확인하기 좋다.",
    estimatedTestTime: "약 1분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "편성이 비교적 단순해 낮은 전자 저음과 보컬의 관계를 집중해서 들을 수 있다. 초저음은 단순히 진동이 강한지가 아니라 낮은 음의 시작, 지속, 감쇠가 구분되고 보컬을 가리지 않는지가 중요하다. 중앙 보컬과 겹쳐지는 코러스의 폭도 확인한다. 작은 이어폰에서는 가장 낮은 대역이 약하게 느껴질 수 있지만 이것만으로 전체 음질이 낮다고 판단하지 않는다. 반대로 저음이 크게 부풀어 오르면 처음에는 풍성해도 박자와 보컬의 명료도가 손상될 수 있다.",
    listeningFocus: ["초저음의 시작과 감쇠", "중앙 리드 보컬과 코러스 폭", "저음이 보컬 자음을 가리는지", "작은 타격음의 위치"],
    listeningGuide: unverifiedGuide(["초저음의 시작과 감쇠", "중앙 리드 보컬과 코러스 폭", "저음이 보컬 자음을 가리는지", "작은 타격음의 위치"]),
    goodPlaybackExamples: ["낮은 대역이 느껴지면서도 각 박자의 윤곽과 보컬이 유지된다.", "리드 보컬은 중앙, 코러스는 주변으로 자연스럽게 펼쳐진다."],
    warningSigns: ["저음이 한 음처럼 웅웅거리며 길게 남는다.", "보컬이 저음 뒤로 밀리거나 자음만 날카롭게 남는다."],
    evaluationFields: ["sub-bass", "midrange", "imaging", "bass-control"],
    freeMemoDefault: "",
    nextTrackIds: ["james-blake-limit-to-your-love", "bibi-vengeance"],
    comparisonTrackIds: ["newjeans-ditto", "billie-eilish-bad-guy"],
    externalServices: serviceSearchLinks("Lorde", "Royals"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "chris-jones-no-sanctuary-here",
    title: "No Sanctuary Here",
    artist: "Chris Jones",
    album: "Roadhouses & Automobiles",
    releaseInfo: "2003",
    country: "미국",
    isKorean: false,
    genres: ["블루스", "포크 록", "오디오파일"],
    vocalType: "male",
    performanceType: "acoustic-mixed",
    ensembleSize: "medium",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "bass-control",
    secondaryCategories: ["midrange", "imaging", "timbre"],
    oneLineReason: "깊은 저음, 굵은 남성 보컬과 공간 잔향의 균형을 빠르게 확인할 수 있다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "낮고 묵직한 반주와 굵은 남성 보컬이 함께 있어 저음의 양, 제어력, 중음의 몸통을 구분하는 데 유용하다. 좋은 재생에서는 저역이 충분한 무게를 주면서도 보컬의 발음과 기타 질감이 사라지지 않는다. 녹음 자체가 풍성하고 입체적으로 들리도록 제작된 편이므로, 이 곡 하나만으로 모든 음원의 공간감이나 저음 성능을 일반화하지 않는다. 특히 더 큰 음량은 저음과 디테일을 더 인상적으로 느끼게 하므로 비교 전 음량을 맞춰야 한다.",
    listeningFocus: ["낮은 반주의 무게와 음정", "남성 보컬의 가슴 울림과 발음", "기타와 타악기의 위치", "잔향이 저음과 겹치는 정도"],
    listeningGuide: unverifiedGuide(["낮은 반주의 무게와 음정", "남성 보컬의 가슴 울림과 발음", "기타와 타악기의 위치", "잔향이 저음과 겹치는 정도"]),
    goodPlaybackExamples: ["저음이 깊지만 보컬의 중심과 기타의 결이 선명하다.", "공간의 잔향이 악기 뒤로 펼쳐지고 전면을 흐리지 않는다."],
    warningSigns: ["저음과 보컬의 낮은 성분이 겹쳐 답답하게 들린다.", "공간 효과가 과장되어 모든 소리가 멀게 느껴진다."],
    evaluationFields: ["bass-control", "midrange", "imaging", "timbre"],
    freeMemoDefault: "",
    nextTrackIds: ["tracy-chapman-fast-car", "hugh-masekela-stimela"],
    comparisonTrackIds: ["michael-jackson-billie-jean", "dean-half-moon"],
    externalServices: serviceSearchLinks("Chris Jones", "No Sanctuary Here"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "fleetwood-mac-dreams",
    title: "Dreams",
    artist: "Fleetwood Mac",
    album: "Rumours",
    releaseInfo: "1977",
    country: "영국·미국",
    isKorean: false,
    genres: ["록", "소프트 록"],
    vocalType: "female",
    performanceType: "acoustic-mixed",
    ensembleSize: "medium",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "timbre",
    secondaryCategories: ["bass-control", "comfort", "midrange"],
    oneLineReason: "보컬, 드럼, 베이스와 기타가 과장되지 않게 어우러져 전체 밸런스와 장시간 편안함을 보기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "반복되는 드럼과 베이스, 차분한 여성 보컬, 기타 레이어가 균형 있게 배치되어 특정 대역이 지나치게 튀는지 살피기 좋다. 저음은 리듬을 지탱하지만 보컬을 압도해서는 안 되고, 고역 타악은 선명하되 계속 신경 쓰일 정도로 날카롭지 않아야 한다. 이 곡은 극단적인 초저음이나 대규모 다이내믹보다 전반적인 음색 균형과 피로도 확인에 적합하다. 원본과 여러 리마스터의 음색 및 음량 차이가 있을 수 있으므로 최종 채택 버전을 기록한다.",
    listeningFocus: ["드럼과 베이스의 반복 리듬", "여성 보컬의 자연스러운 두께", "기타 레이어의 좌우 배치", "2분 이상 들었을 때 고역 피로"],
    listeningGuide: unverifiedGuide(["드럼과 베이스의 반복 리듬", "여성 보컬의 자연스러운 두께", "기타 레이어의 좌우 배치", "2분 이상 들었을 때 고역 피로"]),
    goodPlaybackExamples: ["어느 한 대역도 음악 전체를 지배하지 않고 리듬이 편안하게 이어진다.", "보컬과 악기가 부드럽지만 세부가 지나치게 흐려지지 않는다."],
    warningSigns: ["저음이 부풀어 박자가 느슨해진다.", "고역 타악과 보컬 자음이 반복적으로 귀를 찌른다."],
    evaluationFields: ["timbre", "bass-control", "comfort", "midrange"],
    freeMemoDefault: "",
    nextTrackIds: ["cranberries-dreams", "yoo-jae-ha-because-i-love-you"],
    comparisonTrackIds: ["michael-jackson-billie-jean", "norah-jones-dont-know-why"],
    externalServices: serviceSearchLinks("Fleetwood Mac", "Dreams"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "hans-zimmer-mountains",
    title: "Mountains",
    artist: "Hans Zimmer",
    album: "Interstellar: Original Motion Picture Soundtrack",
    releaseInfo: "2014",
    country: "독일",
    isKorean: false,
    genres: ["영화 음악", "오케스트라", "앰비언트"],
    vocalType: "instrumental",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "dynamics",
    secondaryCategories: ["sub-bass", "detail", "imaging"],
    oneLineReason: "작은 시작에서 거대한 음향으로 확장될 때 다이내믹, 저역 여유와 레이어 유지 능력을 확인할 수 있다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "반복되는 작은 리듬 위에 오르간과 오케스트라 층이 점차 더해져 기기의 다이내믹 여유와 복잡한 구간의 분리도를 확인하기 좋다. 큰 소리가 단순히 거칠어지거나 납작하게 눌리지 않고, 낮은 대역의 압력과 중·고역의 선율이 함께 유지되는지 듣는다. 영화 음악의 거대한 스케일은 음량을 높이고 싶게 만들지만, 큰 음량 자체가 기기의 성능 차이처럼 느껴질 수 있으므로 편안한 수준을 유지한다. 원래 녹음의 강한 저역과 잔향을 기기 왜곡과 구분한다.",
    listeningFocus: ["초반 작은 반복음의 선명도", "오르간 저역의 확장과 안정성", "편성이 커질 때 선율 레이어", "최대 구간에서 압축과 거친 고역"],
    listeningGuide: unverifiedGuide(["초반 작은 반복음의 선명도", "오르간 저역의 확장과 안정성", "편성이 커질 때 선율 레이어", "최대 구간에서 압축과 거친 고역"]),
    goodPlaybackExamples: ["작은 시작과 큰 절정의 차이가 크면서도 절정에서 정보가 무너지지 않는다.", "저역의 스케일이 커져도 중역 선율을 계속 따라갈 수 있다."],
    warningSigns: ["절정에서 전체 소리가 납작하고 답답해진다.", "저역이 과도하게 흔들리거나 고역이 거칠게 찢어진다."],
    evaluationFields: ["dynamics", "sub-bass", "detail", "imaging"],
    freeMemoDefault: "",
    nextTrackIds: ["aaron-copland-fanfare", "park-hyo-shin-wild-flower"],
    comparisonTrackIds: ["daft-punk-giorgio-by-moroder", "next-lazenca-save-us"],
    externalServices: serviceSearchLinks("Hans Zimmer", "Mountains"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "park-hyo-shin-wild-flower",
    title: "야생화",
    artist: "박효신",
    album: "야생화",
    releaseInfo: "2014 · 싱글",
    country: "대한민국",
    isKorean: true,
    genres: ["발라드", "팝"],
    vocalType: "male",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "long",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "dynamics",
    secondaryCategories: ["midrange", "treble", "detail"],
    oneLineReason: "작은 보컬에서 강한 고음과 대편성으로 확장되어 보컬 다이내믹과 혼잡도를 확인하기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "초반의 비교적 절제된 보컬과 피아노에서 후반의 강한 보컬, 현악과 밴드 편성으로 확대되는 흐름이 뚜렷하다. 보컬이 커질 때 단순히 소리만 커지는 것이 아니라 호흡, 발음과 감정의 미세한 변화가 유지되는지 확인한다. 후반부에서 고음이 자극적으로 찢어지거나 반주가 한 덩어리로 뭉치지 않는지도 중요하다. 원래 가창과 믹스에 포함된 강한 에너지를 모두 기기의 고역 과장으로 판단하지 말고, 같은 구간을 여러 음량에서 비교한다.",
    listeningFocus: ["초반 보컬의 호흡과 피아노 잔향", "보컬 음량이 커질 때 중심 유지", "현악과 드럼이 추가될 때 분리", "후반 고음의 자극과 압축 여부"],
    listeningGuide: unverifiedGuide(["초반 보컬의 호흡과 피아노 잔향", "보컬 음량이 커질 때 중심 유지", "현악과 드럼이 추가될 때 분리", "후반 고음의 자극과 압축 여부"]),
    goodPlaybackExamples: ["작은 보컬의 세부와 큰 보컬의 힘이 모두 자연스럽게 이어진다.", "후반부가 커져도 보컬, 현악, 드럼의 층을 구분할 수 있다."],
    warningSigns: ["고음에서 목소리가 얇고 날카롭게 변한다.", "대편성 구간이 한 덩어리로 뭉치고 피아노가 사라진다."],
    evaluationFields: ["dynamics", "midrange", "treble", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["ailee-i-will-go-to-you-like-first-snow", "younha-event-horizon"],
    comparisonTrackIds: ["hans-zimmer-mountains", "adele-someone-like-you"],
    externalServices: serviceSearchLinks("박효신", "야생화"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "iu-good-day",
    title: "좋은 날",
    artist: "아이유",
    album: "Real",
    releaseInfo: "2010",
    country: "대한민국",
    isKorean: true,
    genres: ["K-pop", "팝", "오케스트라 팝"],
    vocalType: "female",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "treble",
    secondaryCategories: ["midrange", "detail", "dynamics"],
    oneLineReason: "밝은 여성 보컬과 밀도 높은 반주, 후반 고음에서 자극·압축·분리도를 확인하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "밝은 보컬과 여러 악기가 촘촘하게 배치되어 중·고역의 균형과 혼잡도를 비교하기 좋다. 핵심은 높은 음이 얼마나 크게 들리는지가 아니라 음정과 발음이 유지되고, 반주가 함께 커져도 보컬이 거칠게 찢어지지 않는지 확인하는 것이다. 치찰음은 `ㅅ`과 같은 자음이 과도하게 튀는 현상으로, 녹음과 발성에도 영향을 받는다. 한 구간의 자극만으로 기기를 단정하지 말고 다른 여성 보컬 곡과 함께 비교한다. 스트리밍의 리마스터 여부를 기록한다.",
    listeningFocus: ["밝은 보컬의 자음과 모음 균형", "현악·브라스·리듬 악기의 분리", "후렴에서 보컬 중심 유지", "후반 고음의 거칠음과 압축"],
    listeningGuide: unverifiedGuide(["밝은 보컬의 자음과 모음 균형", "현악·브라스·리듬 악기의 분리", "후렴에서 보컬 중심 유지", "후반 고음의 거칠음과 압축"]),
    goodPlaybackExamples: ["고음이 시원하게 올라가면서도 자음이 칼날처럼 튀지 않는다.", "밀도 높은 반주에서도 보컬과 주요 악기를 따라갈 수 있다."],
    warningSigns: ["고음이 얇고 금속적으로 변한다.", "반주가 커질 때 보컬이 묻히거나 전체가 납작해진다."],
    evaluationFields: ["treble", "midrange", "detail", "dynamics"],
    freeMemoDefault: "",
    nextTrackIds: ["taeyeon-invu", "ailee-i-will-go-to-you-like-first-snow"],
    comparisonTrackIds: ["park-hyo-shin-wild-flower", "f-x-4-walls"],
    externalServices: serviceSearchLinks("아이유", "좋은 날"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "newjeans-ditto",
    title: "Ditto",
    artist: "NewJeans",
    album: "OMG",
    releaseInfo: "2022 · 선공개 싱글",
    country: "대한민국",
    isKorean: true,
    genres: ["K-pop", "팝", "볼티모어 클럽"],
    vocalType: "female-group",
    performanceType: "electronic",
    ensembleSize: "medium",
    durationClass: "short",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "imaging",
    secondaryCategories: ["bass-control", "midrange", "detail"],
    oneLineReason: "부드러운 보컬 레이어, 전자 저음과 잔향 효과의 균형을 비교하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "리드 보컬과 겹쳐지는 코러스, 부드러운 전자 저음, 넓게 퍼지는 공간 효과가 함께 있어 레이어와 중앙 이미지의 안정성을 확인하기 좋다. 공간감이 넓다는 이유만으로 위치 표현이 정확하다고 판단하지 말고, 리드 보컬이 중앙에 유지되는지와 주변 보컬·효과음의 거리를 구분한다. 저음은 둥글고 부드러운 성격이지만 보컬의 낮은 부분을 덮거나 리듬을 느리게 만들 정도로 번져서는 안 된다. 원래 믹스의 몽환적인 질감을 기기의 흐림과 구분한다.",
    listeningFocus: ["리드 보컬의 중앙 위치", "주변 코러스의 폭과 거리", "전자 저음의 둥근 질감과 제어", "작은 효과음과 잔향의 층"],
    listeningGuide: unverifiedGuide(["리드 보컬의 중앙 위치", "주변 코러스의 폭과 거리", "전자 저음의 둥근 질감과 제어", "작은 효과음과 잔향의 층"]),
    goodPlaybackExamples: ["중앙 보컬은 또렷하고 코러스와 효과는 주변에 자연스럽게 펼쳐진다.", "저음이 부드러우면서 박자의 시작과 끝을 구분할 수 있다."],
    warningSigns: ["공간 효과 때문에 보컬 중심이 흔들리거나 비어 보인다.", "저음과 잔향이 겹쳐 전체가 흐릿해진다."],
    evaluationFields: ["imaging", "bass-control", "midrange", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["taeyeon-invu", "lorde-royals"],
    comparisonTrackIds: ["dean-half-moon", "aespa-supernova"],
    externalServices: serviceSearchLinks("NewJeans", "Ditto"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "taeyeon-invu",
    title: "INVU",
    artist: "태연",
    album: "INVU",
    releaseInfo: "2022",
    country: "대한민국",
    isKorean: true,
    genres: ["K-pop", "신스팝", "댄스 팝"],
    vocalType: "female",
    performanceType: "electronic",
    ensembleSize: "medium",
    durationClass: "short",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "treble",
    secondaryCategories: ["imaging", "midrange", "sub-bass"],
    oneLineReason: "중앙 여성 보컬과 넓게 배치된 신스, 밝은 고역과 전자 저음의 균형을 확인하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "리드 보컬은 중앙에 비교적 선명하게 배치되고 신시사이저와 코러스는 넓게 펼쳐져 중앙과 주변의 대비를 확인할 수 있다. 밝은 고역이 선명하면서도 자음과 숨소리가 과도하게 날카롭지 않은지, 전자 저음이 보컬의 몸통을 가리지 않는지 듣는다. 신스의 넓은 배치는 원래 믹스의 특징이므로, 무대가 넓게 들린다는 사실만으로 기기의 이미징이 정확하다고 단정하지 않는다. 다른 어쿠스틱 보컬 곡과 함께 비교해야 음색 특성을 더 잘 구분할 수 있다.",
    listeningFocus: ["중앙 보컬의 고정감", "신스와 코러스의 좌우 확장", "고역 자음과 숨소리의 자극", "전자 저음과 보컬 몸통의 분리"],
    listeningGuide: unverifiedGuide(["중앙 보컬의 고정감", "신스와 코러스의 좌우 확장", "고역 자음과 숨소리의 자극", "전자 저음과 보컬 몸통의 분리"]),
    goodPlaybackExamples: ["보컬 중심이 안정되고 주변 신스가 넓지만 위치가 흐려지지 않는다.", "고역이 밝아도 오래 들을 때 자극이 누적되지 않는다."],
    warningSigns: ["자음과 숨소리가 음악보다 앞서 튄다.", "넓은 신스가 중앙 보컬까지 흐리게 만든다."],
    evaluationFields: ["treble", "imaging", "midrange", "sub-bass"],
    freeMemoDefault: "",
    nextTrackIds: ["f-x-4-walls", "aespa-next-level"],
    comparisonTrackIds: ["iu-good-day", "newjeans-ditto"],
    externalServices: serviceSearchLinks("태연", "INVU"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "gidle-tomboy",
    title: "TOMBOY",
    artist: "(여자)아이들",
    album: "I NEVER DIE",
    releaseInfo: "2022",
    country: "대한민국",
    isKorean: true,
    genres: ["K-pop", "얼터너티브 록", "팝 펑크"],
    vocalType: "female-group",
    performanceType: "electronic-mixed",
    ensembleSize: "medium",
    durationClass: "short",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "transient",
    secondaryCategories: ["bass-control", "midrange", "detail"],
    oneLineReason: "강한 킥·베이스와 기타, 여러 보컬 톤이 겹칠 때 타격과 분리도를 비교하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "짧고 강한 리듬 타격, 왜곡 기타, 전자 저음과 서로 다른 보컬 톤이 함께 등장해 속도와 분리도를 확인하기 좋다. 타격음이 크다고 트랜지언트가 정확한 것은 아니며, 시작이 빠르고 멈춤이 분명한지 들어야 한다. 보컬이 거칠게 표현되는 부분은 곡의 제작 의도일 수 있으므로 모든 거친 질감을 기기 왜곡으로 판단하지 않는다. 후렴에서 기타와 저음이 보컬을 가리지 않고, 여러 보컬의 음색 차이가 유지되는지 비교한다.",
    listeningFocus: ["킥의 첫 타격과 감쇠", "베이스와 왜곡 기타의 분리", "멤버별 보컬 음색 차이", "후렴의 높은 밀도에서 중심 유지"],
    listeningGuide: unverifiedGuide(["킥의 첫 타격과 감쇠", "베이스와 왜곡 기타의 분리", "멤버별 보컬 음색 차이", "후렴의 높은 밀도에서 중심 유지"]),
    goodPlaybackExamples: ["강한 타격이 빠르고 단단하지만 잔향이 다음 박자를 덮지 않는다.", "보컬, 기타와 저음이 겹쳐도 각 층을 구분할 수 있다."],
    warningSigns: ["타격이 크기만 하고 둔하게 번진다.", "왜곡 기타와 고역 보컬이 합쳐져 거친 소음처럼 들린다."],
    evaluationFields: ["transient", "bass-control", "midrange", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["aespa-supernova", "yb-flying-butterfly"],
    comparisonTrackIds: ["michael-jackson-billie-jean", "bibi-vengeance"],
    externalServices: serviceSearchLinks("(여자)아이들", "TOMBOY"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "younha-event-horizon",
    title: "사건의 지평선",
    artist: "윤하",
    album: "END THEORY : Final Edition",
    releaseInfo: "2022",
    country: "대한민국",
    isKorean: true,
    genres: ["팝 록", "K-pop"],
    vocalType: "female",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "dynamics",
    secondaryCategories: ["treble", "midrange", "detail"],
    oneLineReason: "피아노와 보컬에서 밴드 편성으로 확장될 때 밀도, 고역 자극과 보컬 중심을 확인하기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "초반의 피아노와 보컬, 이후 드럼·기타·베이스가 더해지는 흐름을 통해 작은 편성과 큰 편성의 차이를 비교할 수 있다. 후렴에서 보컬이 강해질 때 자음이 날카롭게 튀지 않고 몸통과 음정이 유지되는지, 심벌과 기타가 보컬을 덮지 않는지 확인한다. 밝고 에너지 있는 믹스 자체를 기기의 고역 과장으로 즉시 판단하지 말고, 잔잔한 어쿠스틱 곡과 교차 비교한다. 음량이 조금만 달라도 후렴의 인상이 크게 달라질 수 있다.",
    listeningFocus: ["초반 피아노 어택과 보컬 거리", "밴드가 들어오는 순간의 다이내믹", "후렴 보컬과 심벌의 고역 균형", "기타·베이스·드럼의 분리"],
    listeningGuide: unverifiedGuide(["초반 피아노 어택과 보컬 거리", "밴드가 들어오는 순간의 다이내믹", "후렴 보컬과 심벌의 고역 균형", "기타·베이스·드럼의 분리"]),
    goodPlaybackExamples: ["편성이 커질수록 스케일이 증가하지만 보컬과 피아노의 핵심이 유지된다.", "심벌이 선명하면서 보컬 자음과 충돌하지 않는다."],
    warningSigns: ["후렴에서 전체가 한꺼번에 앞으로 몰려 답답하다.", "보컬 고음과 심벌이 겹쳐 지속적인 자극을 만든다."],
    evaluationFields: ["dynamics", "treble", "midrange", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["park-hyo-shin-wild-flower", "yb-flying-butterfly"],
    comparisonTrackIds: ["iu-good-day", "akmu-how-can-i-love-heartbreak"],
    externalServices: serviceSearchLinks("윤하", "사건의 지평선"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "ailee-i-will-go-to-you-like-first-snow",
    title: "첫눈처럼 너에게 가겠다",
    artist: "에일리",
    album: "도깨비 OST Part 9",
    releaseInfo: "2017",
    country: "대한민국",
    isKorean: true,
    genres: ["OST", "발라드"],
    vocalType: "female",
    performanceType: "acoustic-mixed",
    ensembleSize: "large",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "beginner",
    primaryCategory: "midrange",
    secondaryCategories: ["dynamics", "timbre", "treble"],
    oneLineReason: "강한 여성 보컬과 피아노·현악 배경을 통해 보컬의 힘, 호흡과 반주 분리를 확인하기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "초반의 보컬과 피아노는 중음의 자연스러움과 호흡을 보기 좋고, 후반 현악과 타악이 더해지는 구간은 다이내믹과 혼잡도를 확인하기 좋다. 보컬이 강해질 때 음량만 커지는 것이 아니라 발음, 몸통과 공간의 잔향이 함께 유지되는지 듣는다. 밝은 고음이 시원하게 들리는 것과 치찰음이나 거친 왜곡이 생기는 것은 구분해야 한다. OST 특유의 감정적 대편성은 원래 녹음의 특징이므로, 다른 단순 편성 보컬 곡과 함께 비교한다.",
    listeningFocus: ["초반 호흡과 발음의 자연스러움", "피아노와 보컬의 거리", "현악이 추가될 때 층의 분리", "강한 고음에서 거칠음과 압축"],
    listeningGuide: unverifiedGuide(["초반 호흡과 발음의 자연스러움", "피아노와 보컬의 거리", "현악이 추가될 때 층의 분리", "강한 고음에서 거칠음과 압축"]),
    goodPlaybackExamples: ["보컬의 힘과 두께가 유지되고 피아노·현악이 뒤에서 자연스럽게 받친다.", "고음이 커져도 자음과 모음의 균형이 무너지지 않는다."],
    warningSigns: ["보컬이 얇아지고 자음만 앞으로 튄다.", "현악과 잔향이 보컬 주변을 덮어 위치가 흐려진다."],
    evaluationFields: ["midrange", "dynamics", "timbre", "treble"],
    freeMemoDefault: "",
    nextTrackIds: ["iu-good-day", "park-hyo-shin-wild-flower"],
    comparisonTrackIds: ["norah-jones-dont-know-why", "adele-someone-like-you"],
    externalServices: serviceSearchLinks("에일리", "첫눈처럼 너에게 가겠다"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "yoo-jae-ha-because-i-love-you",
    title: "그대 내 품에",
    artist: "유재하",
    album: "사랑하기 때문에",
    releaseInfo: "1987",
    country: "대한민국",
    isKorean: true,
    genres: ["발라드", "팝", "싱어송라이터"],
    vocalType: "male",
    performanceType: "acoustic-mixed",
    ensembleSize: "medium",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "timbre",
    secondaryCategories: ["midrange", "comfort", "detail"],
    oneLineReason: "남성 보컬과 어쿠스틱 악기의 질감, 오래 들어도 편안한 중역과 녹음 시대의 특성을 확인하기 좋다.",
    estimatedTestTime: "약 2분",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "보컬과 어쿠스틱 악기의 중역이 중심이 되는 곡으로, 목소리의 몸통과 악기 음색이 자연스럽게 이어지는지 확인하기 좋다. 현대 팝처럼 극단적인 초저음과 초고역을 기대하기보다, 녹음 시대의 특성을 존중하면서 보컬의 감정과 반주의 결이 유지되는지 듣는다. 리마스터 버전에 따라 밝기, 저음 양과 전체 음량이 달라질 수 있으므로 버전을 반드시 기록한다. 세부를 강조하는 기기가 오래된 녹음의 노이즈까지 부각할 수 있지만, 노이즈가 많이 들린다고 해상도가 항상 더 높다고 단정할 수 없다.",
    listeningFocus: ["남성 보컬의 몸통과 발음", "피아노·현악 등 반주의 자연스러운 음색", "잔향과 녹음 노이즈의 정도", "2분 이상 감상했을 때 편안함"],
    listeningGuide: unverifiedGuide(["남성 보컬의 몸통과 발음", "피아노·현악 등 반주의 자연스러운 음색", "잔향과 녹음 노이즈의 정도", "2분 이상 감상했을 때 편안함"]),
    goodPlaybackExamples: ["보컬이 얇거나 답답하지 않고 반주와 자연스럽게 섞인다.", "오래된 녹음의 질감을 보여 주면서 음악적 중심을 잃지 않는다."],
    warningSigns: ["고역 노이즈와 자음만 과도하게 강조된다.", "중저음이 부풀어 보컬과 반주가 답답하게 겹친다."],
    evaluationFields: ["timbre", "midrange", "comfort", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["kim-kwang-seok-wind-blows", "yang-hee-eun-love-loneliness"],
    comparisonTrackIds: ["fleetwood-mac-dreams", "norah-jones-dont-know-why"],
    externalServices: serviceSearchLinks("유재하", "그대 내 품에"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "leenalchi-tiger-is-coming",
    title: "범 내려온다",
    artist: "이날치",
    album: "수궁가",
    releaseInfo: "2020",
    country: "대한민국",
    isKorean: true,
    genres: ["얼터너티브 팝", "국악 크로스오버", "전자음악"],
    vocalType: "mixed-group",
    performanceType: "electronic-mixed",
    ensembleSize: "medium",
    durationClass: "medium",
    durationSeconds: null,
    difficulty: "intermediate",
    primaryCategory: "detail",
    secondaryCategories: ["bass-control", "transient", "midrange"],
    oneLineReason: "반복적인 베이스, 빠른 리듬과 여러 보컬이 겹치는 구간에서 속도와 분리도를 확인하기 좋다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "반복되는 베이스와 타악적 리듬 위에 여러 보컬이 교차해 빠른 소리의 시작과 끝, 보컬 분리와 리듬의 탄력을 확인할 수 있다. 판소리 기반 발성은 일반 팝 보컬과 배음과 강세가 다르므로, 서구 팝의 부드러운 보컬 기준만으로 거칠다고 평가하지 않는다. 저음이 많게 들리는 것보다 반복 패턴의 음정과 박자가 또렷하고, 보컬이 겹쳐도 각 목소리의 움직임을 따라갈 수 있는지가 중요하다. 기기 특성과 장르 고유의 음색을 분리해서 기록한다.",
    listeningFocus: ["반복 베이스의 음정과 멈춤", "여러 보컬의 교차와 위치", "빠른 자음과 리듬의 선명도", "후렴의 높은 밀도에서 분리"],
    listeningGuide: unverifiedGuide(["반복 베이스의 음정과 멈춤", "여러 보컬의 교차와 위치", "빠른 자음과 리듬의 선명도", "후렴의 높은 밀도에서 분리"]),
    goodPlaybackExamples: ["베이스가 강해도 박자와 음정이 흐려지지 않는다.", "여러 보컬이 동시에 나와도 각 흐름과 발음을 따라갈 수 있다."],
    warningSigns: ["베이스가 웅웅거리며 리듬을 느리게 만든다.", "강한 발성이 모두 날카롭고 같은 위치에서 겹쳐 들린다."],
    evaluationFields: ["detail", "bass-control", "transient", "midrange"],
    freeMemoDefault: "",
    nextTrackIds: ["aespa-supernova", "gidle-tomboy"],
    comparisonTrackIds: ["snarky-puppy-lingus", "dean-half-moon"],
    externalServices: serviceSearchLinks("이날치", "범 내려온다"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
  {
    id: "song-sohee-arirang",
    title: "아리랑",
    artist: "송소희",
    album: "TODO_VERIFY_METADATA",
    releaseInfo: "TODO_VERIFY_RELEASE",
    country: "대한민국",
    isKorean: true,
    genres: ["국악", "민요", "보컬"],
    vocalType: "female",
    performanceType: "acoustic-mixed",
    ensembleSize: "variable",
    durationClass: "unknown",
    durationSeconds: null,
    difficulty: "advanced",
    primaryCategory: "timbre",
    secondaryCategories: ["midrange", "imaging", "detail"],
    oneLineReason: "전통 창법의 배음, 긴 호흡과 공간 잔향을 통해 보컬 음색과 자연스러움을 비교하기 위한 검수 예정 곡이다.",
    estimatedTestTime: "약 1분 30초",
    favoriteDefault: false,
    completedDefault: false,
    whySuitable: "한국 전통 창법은 일반 팝 보컬과 다른 배음, 발성 강도와 장식음을 포함하므로 기기가 복잡한 보컬 질감을 얼마나 자연스럽게 표현하는지 확인하는 데 의미가 있다. 다만 여러 공연·방송·앨범 버전의 편성, 음질과 잔향이 크게 다르므로 최종 버전을 확정하기 전에는 실제 타임라인과 세부 평가를 공개하지 않는다. 강한 배음을 단순한 치찰음이나 왜곡으로 오해하지 말고, 목소리의 중심·호흡·공간 잔향이 분리되는지 듣는다. 국악을 서구 악기 중심의 기준 하나로 순위를 매기지 않는다.",
    listeningFocus: ["긴 호흡과 음정의 연결", "전통 창법의 배음과 목소리 중심", "반주 악기와 보컬의 거리", "공연장 또는 스튜디오 잔향"],
    listeningGuide: unverifiedGuide(["긴 호흡과 음정의 연결", "전통 창법의 배음과 목소리 중심", "반주 악기와 보컬의 거리", "공연장 또는 스튜디오 잔향"]),
    goodPlaybackExamples: ["강한 배음이 선명하면서 목소리의 중심과 호흡이 유지된다.", "잔향이 길어도 발음과 반주 악기의 위치를 구분할 수 있다."],
    warningSigns: ["배음이 얇고 날카로운 소리로만 재생된다.", "잔향이 보컬을 덮어 발음과 음정 변화가 흐려진다."],
    evaluationFields: ["timbre", "midrange", "imaging", "detail"],
    freeMemoDefault: "",
    nextTrackIds: ["sumi-jo-nella-fantasia", "yang-hee-eun-love-loneliness"],
    comparisonTrackIds: ["ailee-i-will-go-to-you-like-first-snow", "yoo-jae-ha-because-i-love-you"],
    externalServices: serviceSearchLinks("송소희", "아리랑"),
    versionInfo: {
      preferredVersion: "명시된 앨범의 공식 음원 버전",
      timelineVerified: false,
      metadataStatus: "TODO_VERIFY",
      serviceVersionNote: "서비스별 마스터, 음량 정규화, 리마스터 및 공간 음향 적용 여부를 비교 전에 기록",
    },
    sources: {
      status: "TODO_VERIFY",
      required: ["아티스트 또는 음반사 공식 디스코그래피", "공식 스트리밍 앨범 메타데이터", "최종 채택 음원의 제공 페이지"],
    },
    addedAt: "2026-10-04",
  },
];

/** 7.3 목록 화면에서 사용할 필터 정의 */
export const AUDIO_TEST_FILTERS = {
  testCategories: [
    "sub-bass",
    "bass-control",
    "midrange",
    "treble",
    "imaging",
    "detail",
    "dynamics",
    "transient",
    "timbre",
    "comfort",
  ] satisfies TestCategory[],
  origin: ["all", "korean", "international"] as const,
  vocalType: [
    "all",
    "instrumental",
    "male",
    "female",
    "mixed",
    "female-group",
    "mixed-group",
  ] as const,
  performanceType: [
    "all",
    "acoustic",
    "electronic",
    "acoustic-mixed",
    "electronic-mixed",
  ] as const,
  ensembleSize: ["all", "small", "medium", "large", "variable"] as const,
  durationClass: ["all", "short", "medium", "long", "unknown"] as const,
  difficulty: ["all", "beginner", "intermediate", "advanced"] as const,
  completion: ["all", "completed", "not-completed"] as const,
};

/** 7.3 목록 정렬 옵션 */
export const AUDIO_TEST_SORT_OPTIONS = [
  { value: "recommended", label: "입문 추천순" },
  { value: "quick-test", label: "빠른 테스트순" },
  { value: "title", label: "곡명순" },
  { value: "artist", label: "아티스트순" },
  { value: "duration", label: "짧은 곡부터" },
  { value: "recent", label: "최근 추가순" },
] as const;

/**
 * 카드 UI 참고:
 * favorite/completed는 사용자 상태 저장소에서 track.id 기준으로 결합한다.
 * durationSeconds가 null인 곡은 검수 전까지 '재생 시간 미확인'으로 표시한다.
 */
export const toTrackCard = (track: AudioTestTrack) => ({
  id: track.id,
  title: track.title,
  artist: track.artist,
  album: track.album,
  originLabel: track.isKorean ? "한국 곡" : track.country,
  primaryCategory: track.primaryCategory,
  secondaryCategories: track.secondaryCategories,
  difficulty: track.difficulty,
  oneLineReason: track.oneLineReason,
  estimatedTestTime: track.estimatedTestTime,
  favorite: track.favoriteDefault,
  completed: track.completedDefault,
  externalServices: track.externalServices,
});

/**
 * 공개 전 필수 검수:
 * - durationSeconds 입력
 * - 공식 음원/영상 직접 링크 확정
 * - 앨범 및 발매 정보 공식 출처 확인
 * - 선택한 음원 버전별 타임라인 초 단위 입력
 * - 실제로 존재하지 않는 nextTrackIds/comparisonTrackIds는 추가 데이터와 연결하거나 제거
 */
